Update package.json
The package.json was missing the 'requests' module. 

This results into the following error once someone runs:

```node ReadDeviceToCloudMessages.js```

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/MyFolder/azure-iot-samples-node-master/iot-hub/Quickstarts/read-d2c-messages/node_modules/@azure/event-hubs/node_modules/ms-rest-azure/lib/credentials/msiVmTokenCredentials.js:12:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)